site:
  title: Cookbook
  start_page: cookbook::book.adoc
  robots: allow
content:
  sources:
  - url: https://github.com/stefanfreitag/cookbook.git
    branches: master

ui:
  bundle:
    url: https://github.com/stefanfreitag/cookbook_antora_ui/raw/main/build/ui-bundle.zip
    snapshot: false
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
output: 
  clean: true
  dir: ./docs
